version: '3'
services:
  discovery:
    image: microservice-docker-discovery:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - appbient
  config:
    image: microservice-docker-config:0.0.1-SNAPSHOT
    links:
      - discovery
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
    ports:
      - 8888:8888
    networks:
      - appbient
  appbient-microservice-evento:
    image: microservice-docker-appbient-microservice-evento:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8082:8082
    networks:
      - appbient
  admin-service:
    image: microservice-docker-admin-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8085:8085
    networks:
      - appbient
networks:
  appbient: