version: '3'
services:
  discovery:
    image: microservice-docker-discovery:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - appbient
  config:
    image: microservice-docker-config:0.0.1-SNAPSHOT
    links:
      - discovery
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
    ports:
      - 8888:8888
    networks:
      - appbient
  appbient_microservice_usuarios:
    image: microservice-docker-appbient_microservice_usuarios:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
        - discovery
        - config
    ports:
      - 8081:8081
    networks:
      - appbient
  appbient-microservice-evento:
    image: microservice-docker-appbient-microservice-evento:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8082:8082
    networks:
      - appbient
  appbient-microservice-proyectos:
    image: microservice-docker-appbient-microservice-proyectos:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8083:8083
    networks:
      - appbient
  appbient_microservice_foros:
    image: microservice-docker-appbient_microservice_foros:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8084:8084
    networks:
      - appbient
  admin-service:
    image: microservice-docker-admin-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8085:8085
    networks:
      - appbient
  gateway-service:
    image: microservice-docker-gateway-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8080:8080
    networks:
      - appbient
networks:
  appbient: