version: '3'
services:
  discovery:
    image: microservice-docker-discovery:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
  config:
    image: microservice-docker-config:0.0.1-SNAPSHOT
    links:
      - discovery
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
    ports:
      - 8888:8888
  appbient-microservice-foro:
    image: microservice-docker-appbient_microservice_foro:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    restart: on-failure
    depends_on:
      - discovery
      - config
    ports:
      - 8084:8084
  appbient-microservice-proyecto:
    image: microservice-docker-appbient-microservice-proyecto:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    restart: on-failure
    depends_on:
        - discovery
        - config
    ports:
      - 8083:8083
  appbient_microservice_usuarios:
    image: microservice-docker-appbient_microservice_usuarios:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    restart: on-failure
    depends_on:
        - discovery
        - config
    ports:
      - 8081:8081
  appbient-microservice-evento:
    image: microservice-docker-appbient-microservice-evento:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    restart: on-failure
    depends_on:
        - discovery
        - config
    ports:
      - 8082:8082
